# Generated by Django 4.0.5 on 2022-07-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('is_deleted', models.CharField(max_length=10)),
            ],
        ),
    ]
