# Generated by Django 4.0.5 on 2022-07-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cdur', models.IntegerField()),
                ('ccat', models.CharField(max_length=50)),
                ('cprice', models.IntegerField()),
            ],
        ),
    ]
